using ProcurementAiApi.LocalRAG.Application.DTOs;
using ProcurementAiApi.LocalRAG.Application.Interfaces;
using System.Net.Http.Json;
using System.Text.Json;
using System.Text.RegularExpressions;

namespace ProcurementAiApi.LocalRAG.Infrastructure.Ollamas;

public class OllamaLlmService : ILlmService
{
    private readonly HttpClient _httpClient;

    public OllamaLlmService(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }

    public async Task<string> GenerateAsync(string prompt, CancellationToken cancellationToken = default)
    {
        var request = new
        {
            model = "qwen3:4b",
            prompt = prompt,
            stream = false,
            options = new
            {
                temperature = 0.1,
                num_predict = 300
            }
        };

        var response = await _httpClient.PostAsJsonAsync("/api/generate", request, cancellationToken);
        response.EnsureSuccessStatusCode();

        // 1. Enable Case Insensitive Deserialization for JSON response
        var jsonOptions = new JsonSerializerOptions
        {
            PropertyNameCaseInsensitive = true
        };

        var result = await response.Content.ReadFromJsonAsync<OllamaGenerateResponse>(jsonOptions, cancellationToken);

        var rawAnswer = result?.Response ?? string.Empty;

        // 2. Remove thinking tags
        var cleanedAnswer = Regex.Replace(rawAnswer, @"<think>[\s\S]*?</think>", "", RegexOptions.IgnoreCase).Trim();

        // 3. Fallback: If stripping <think> emptied the string, extract text inside <think> or return raw response
        if (string.IsNullOrWhiteSpace(cleanedAnswer) && !string.IsNullOrWhiteSpace(rawAnswer))
        {
            cleanedAnswer = Regex.Replace(rawAnswer, @"</?think>", "", RegexOptions.IgnoreCase).Trim();
        }

        return string.IsNullOrWhiteSpace(cleanedAnswer) ? "No answer generated by LLM." : cleanedAnswer;
    }
}